# Link do danych: [dane](https://www.kaggle.com/datasets/thedevastator/airbnb-prices-in-european-cities)

In [ ]:
!kaggle datasets download -d thedevastator/airbnb-prices-in-european-cities

Dataset URL: https://www.kaggle.com/datasets/thedevastator/airbnb-prices-in-european-cities
License(s): CC0-1.0
Downloading airbnb-prices-in-european-cities.zip to /content
  0% 0.00/3.91M [00:00<?, ?B/s]
100% 3.91M/3.91M [00:00<00:00, 120MB/s]

In [ ]:
!unzip airbnb-prices-in-european-cities.zip

Archive:  airbnb-prices-in-european-cities.zip
  inflating: amsterdam_weekdays.csv
  inflating: amsterdam_weekends.csv
  inflating: athens_weekdays.csv
  inflating: athens_weekends.csv
  inflating: barcelona_weekdays.csv
  inflating: barcelona_weekends.csv
  inflating: berlin_weekdays.csv
  inflating: berlin_weekends.csv
  inflating: budapest_weekdays.csv
  inflating: budapest_weekends.csv
  inflating: lisbon_weekdays.csv
  inflating: lisbon_weekends.csv
  inflating: london_weekdays.csv
  inflating: london_weekends.csv
  inflating: paris_weekdays.csv
  inflating: paris_weekends.csv
  inflating: rome_weekdays.csv
  inflating: rome_weekends.csv
  inflating: vienna_weekdays.csv
  inflating: vienna_weekends.csv

# Korzystanie z [pandas](https://pandas.pydata.org/).

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('amsterdam_weekdays.csv')

In [ ]:
df.head(6) # pokazuje wiersze na górze

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,1,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772
1,1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,1,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432
2,2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,1,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103
3,3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,2,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663
4,4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,1,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508
5,5,552.808567,Private room,False,True,3.0,False,0,0,8.0,100.0,2,2.131420,1.904668,174.788957,9.255191,225.201662,15.692376,4.87699,52.38966

In [ ]:
df.tail(6)  # pokazuje wiersze na dole zbioru

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
1097,1097,356.197127,Private room,False,True,4.0,True,0,0,10.0,95.0,1,2.169253,0.212113,224.433556,11.883906,291.785726,20.332049,4.91118,52.35718
1098,1098,2486.115342,Entire home/apt,False,False,2.0,False,0,0,10.0,100.0,1,2.375833,1.436054,181.198355,9.594573,225.304203,15.699521,4.85869,52.37677
1099,1099,233.637194,Private room,False,True,2.0,False,1,0,10.0,90.0,1,4.719736,0.322263,108.024880,5.719989,134.775277,9.391335,4.83611,52.34910
1100,1100,317.062311,Private room,False,True,2.0,False,1,0,10.0,92.0,1,0.598355,0.751993,440.476515,23.323524,625.947562,43.616927,4.88897,52.37798
1101,1101,1812.855904,Entire home/apt,False,False,4.0,False,0,0,8.0,84.0,5,1.943020,0.388532,257.948105,13.658524,336.589237,23.454022,4.90688,52.35794
1102,1102,258.008577,Shared room,True,False,2.0,False,0,0,8.0,90.0,1,0.280204,0.516217,533.962653,28.273677,807.492307,56.267226,4.89295,52.37575

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1103 non-null   int64
 1   realSum                     1103 non-null   float64
 2   room_type                   1103 non-null   object
 3   room_shared                 1103 non-null   bool
 4   room_private                1103 non-null   bool
 5   person_capacity             1103 non-null   float64
 6   host_is_superhost           1103 non-null   bool
 7   multi                       1103 non-null   int64
 8   biz                         1103 non-null   int64
 9   cleanliness_rating          1103 non-null   float64
 10  guest_satisfaction_overall  1103 non-null   float64
 11  bedrooms                    1103 non-null   int64
 12  dist                        1103 non-null   float64
 13  metro_dist                  1103 non-null   float64
 14  attr_index                  1103 non-null   float64
 15  attr_index_norm             1103 non-null   float64
 16  rest_index                  1103 non-null   float64
 17  rest_index_norm             1103 non-null   float64
 18  lng                         1103 non-null   float64
 19  lat                         1103 non-null   float64
dtypes: bool(3), float64(12), int64(4), object(1)
memory usage: 149.8+ KB

In [ ]:
df_isna = df.isna()
df_isna.head()

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
True + True

2

In [ ]:
df_isna.sum()

Unnamed: 0                    0
realSum                       0
room_type                     0
room_shared                   0
room_private                  0
person_capacity               0
host_is_superhost             0
multi                         0
biz                           0
cleanliness_rating            0
guest_satisfaction_overall    0
bedrooms                      0
dist                          0
metro_dist                    0
attr_index                    0
attr_index_norm               0
rest_index                    0
rest_index_norm               0
lng                           0
lat                           0
dtype: int64

In [ ]:
list(df.columns)

['Unnamed: 0',
 'realSum',
 'room_type',
 'room_shared',
 'room_private',
 'person_capacity',
 'host_is_superhost',
 'multi',
 'biz',
 'cleanliness_rating',
 'guest_satisfaction_overall',
 'bedrooms',
 'dist',
 'metro_dist',
 'attr_index',
 'attr_index_norm',
 'rest_index',
 'rest_index_norm',
 'lng',
 'lat']

In [ ]:
df.realSum  # ja nie jestem fanem tej metody, będzie błąd w przypadku df.class

0        194.033698
1        344.245776
2        264.101422
3        433.529398
4        485.552926
           ...
1098    2486.115342
1099     233.637194
1100     317.062311
1101    1812.855904
1102     258.008577
Name: realSum, Length: 1103, dtype: float64

In [ ]:
df['realSum']  # ta metoda jest bardziej uniwersalna

0        194.033698
1        344.245776
2        264.101422
3        433.529398
4        485.552926
           ...
1098    2486.115342
1099     233.637194
1100     317.062311
1101    1812.855904
1102     258.008577
Name: realSum, Length: 1103, dtype: float64

In [ ]:
df['realSum'][4]  # teraz dostałem się do index nr 4

485.5529257375859

In [ ]:
df.iloc[0, :]  # teraz korzystam z slicing

Unnamed: 0                               0
realSum                         194.033698
room_type                     Private room
room_shared                          False
room_private                          True
person_capacity                        2.0
host_is_superhost                    False
multi                                    1
biz                                      0
cleanliness_rating                    10.0
guest_satisfaction_overall            93.0
bedrooms                                 1
dist                              5.022964
metro_dist                         2.53938
attr_index                       78.690379
attr_index_norm                   4.166708
rest_index                       98.253896
rest_index_norm                   6.846473
lng                                4.90569
lat                               52.41772
Name: 0, dtype: object

In [ ]:
df.loc['90010111111', 'realSum']  # to działa poprawnie

194.03369812293488

In [ ]:
df.iloc[0, 'realSum']  # to będzie błąd

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

## Zadanie 💪
1.   Wybrać inne miasto
1.   Załadować dane
1.   Sprawdzić czy brakuje danych
1.   Sprawdzić czy nowe dane mają te same kolumny
1.   Pokazać cały 3 wiersz
1.   Pokazać 3, 5, 6 kolumnę

In [ ]:
def get_validate_data(csv_file, columns):
  _df = pd.read_csv(csv_file)  # ładowanie danych
  df_subset = _df.iloc[:, [2, 4, 5]]  # pobranie wybranych zmiennych
  _df_columns = _df.columns
  if columns.equals(_df_columns):  # inny sposób list(df_columns) == list(df_athens_columns)
    return df_subset
  return None

In [ ]:
df_barcelona = pd.read_csv('barcelona_weekends.csv')

In [ ]:
df_barcelona.drop(columns=['room_type']).to_csv('barcelona_weekends_bez_room_type.csv', index=False)

In [ ]:
get_validate_data('budapest_weekends.csv', df.columns)

            room_type  room_private  person_capacity
0     Entire home/apt         False              6.0
1     Entire home/apt         False              6.0
2     Entire home/apt         False              6.0
3     Entire home/apt         False              5.0
4     Entire home/apt         False              4.0
...               ...           ...              ...
1943  Entire home/apt         False              4.0
1944  Entire home/apt         False              3.0
1945  Entire home/apt         False              4.0
1946  Entire home/apt         False              3.0
1947  Entire home/apt         False              3.0

[1948 rows x 3 columns]

In [ ]:
df_subset = get_validate_data('barcelona_weekends_bez_room_type.csv', df.columns)
df_subset